import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ShieldCheck, 
  ArrowRight, 
  CheckCircle2, 
  Sparkles, 
  Compass, 
  UserCheck, 
  ClipboardCheck, 
  Building2, 
  Scale, 
  Flag, 
  ChevronLeft, 
  ChevronRight,
  AlertTriangle,
  Zap,
  Droplet,
  Wifi,
  Car,
  FileCheck2,
  Lock,
  Pause,
  Play,
  Share2
} from 'lucide-react';
import { AnimatedBackground } from './components/AnimatedBackground';
import { FeatureDetailModal, FeatureDetail } from './components/FeatureDetailModal';
import { JoinModal } from './components/JoinModal';

const INTELLIGENCE_FEATURES: FeatureDetail[] = [
  {
    id: 1,
    title: '1. Livability Score',
    tag: '0–100 Score',
    tagColor: 'text-emerald-700 bg-emerald-50 border-emerald-200',
    iconBg: 'bg-emerald-50 text-[#059669] border border-emerald-200',
    icon: ShieldCheck,
    description: 'A 0–100 score for any property, built from six verified data dimensions: electricity reliability, flood risk, mobile network quality, water reliability, safety, and commute/traffic. Every number traces to a real data source — never AI-estimated.',
    metrics: [
      '⚡ Power Reliability',
      '🌊 Flood Vulnerability',
      '📶 4G/5G Network Quality',
      '💧 Water Purity & Supply'
    ],
    dataSources: [
      'DISCO feeder transformer uptime telemetry & historical blackout logs',
      'Hydrological elevation topography & urban drainage basin analysis',
      'Crowd-sourced multi-carrier indoor/outdoor cellular latency benchmarks',
      'Neighborhood security incident reports and verified estate gate logs'
    ],
    benefits: [
      'Calculate true generator fuel expenses before negotiating the lease',
      'Avoid paying advance rent on streets that submerge during rainy season',
      'Confirm reliable remote work connectivity before moving in',
      'Compare standard scores across urban districts with zero bias'
    ],
    operationalDetails: 'Scores are computed using deterministic weighted algorithms against verified field data. AI is strictly prohibited from guessing or generating score values.'
  },
  {
    id: 2,
    title: '2. Neighbourhood Intelligence',
    tag: 'Deep Context',
    tagColor: 'text-blue-700 bg-blue-50 border-blue-200',
    iconBg: 'bg-blue-50 text-blue-600 border border-blue-200',
    icon: Compass,
    description: 'Deeper context behind the score — breaking down individual factor scores, strengths/weaknesses, and data freshness/confidence, so renters understand why a place scores the way it does, not just the number.',
    metrics: [
      '📊 6-Factor Breakdowns',
      '⏳ 90-Day Freshness Window',
      '🔒 Confidence Interval %',
      '🛡️ Gate Curfew & Access'
    ],
    dataSources: [
      'Street-level resident surveys verified via geofenced utility bills',
      'Estate Community Development Association (CDA) bylaws and curfew schedules',
      'Direct municipal water board coverage maps & borehole depth audits',
      'Quarterly road infrastructure maintenance tracking'
    ],
    benefits: [
      'Understand why a neighborhood scored 64 vs 82 with total transparency',
      'Uncover restrictive estate gate closing hours (e.g. 11:00 PM lockouts)',
      'Discover alternate bypass roads to dodge rush-hour gridlock',
      'Know in advance if boreholes require specialized industrial filtration'
    ],
    operationalDetails: 'Intelligence reports update on rolling 90-day intervals. Any score older than 90 days displays a "Verification Due" badge until field checks refresh.'
  },
  {
    id: 3,
    title: '3. Survival Summary',
    tag: 'Gemini Narration',
    tagColor: 'text-emerald-700 bg-emerald-50 border-emerald-200',
    iconBg: 'bg-emerald-50 text-[#059669] border border-emerald-200',
    icon: Sparkles,
    description: 'A plain-English narrative (generated by Gemini) explaining what the score and data mean in practical, everyday terms — AI handles narration only, never computation.',
    metrics: [
      '📝 Plain-English Narrative',
      '🤖 AI Narration Only',
      '🚫 Zero Hallucinations',
      '⏱️ 30-Sec Read Time'
    ],
    dataSources: [
      'Structured Livability Score data strictly fed into constrained system prompts',
      'VerifiRent validated ground-truth fact tables (no open web assumptions)',
      'Deterministic cost-of-living calculators for diesel and water trucking',
      'Seasonal weather historical impact records'
    ],
    benefits: [
      'Translates raw technical metrics into actionable day-to-day expectations',
      'Provides families and diaspora renters with instant, clear lifestyle insights',
      'Explicitly highlights hidden ongoing costs (e.g. generator fuel estimates)',
      'Zero marketing fluff or deceptive real estate sales language'
    ],
    operationalDetails: 'Gemini generates natural language summaries based solely on pre-verified numeric parameters. If a metric is unknown, Gemini states "Unverified" rather than guessing.'
  },
  {
    id: 4,
    title: '4. Comparison Tools',
    tag: 'Side-by-Side',
    tagColor: 'text-indigo-700 bg-indigo-50 border-indigo-200',
    iconBg: 'bg-indigo-50 text-indigo-600 border border-indigo-200',
    icon: Scale,
    description: 'Letting renters compare properties or entire neighbourhoods/areas side by side across livability factors, not just photos and price.',
    metrics: [
      'Side-by-Side Matrix',
      'Total Cost of Living',
      'Commute Trade-offs',
      'Property vs Property'
    ],
    dataSources: [
      'Normalized multi-factor vector comparison algorithms',
      'Historical peak-hour commute times to major commercial hubs',
      'Average monthly estate service charge and power tariff databases',
      'Historical rainy-season flood records across metropolitan districts'
    ],
    benefits: [
      'Reveals total living cost (e.g. lower rent vs significantly higher monthly fuel spend)',
      'Pits different districts against each other in real time with objective numbers',
      'Removes emotional bias and smooth-talking agent pitches from lease choices',
      'Compare up to 4 apartments simultaneously across 18 living dimensions'
    ],
    operationalDetails: 'Comparison metrics use standardized scaling so that disparate areas can be objectively evaluated against common living standards.'
  }
];

const VERIFICATION_SERVICES: FeatureDetail[] = [
  {
    id: 5,
    title: '5. Physical Inspection',
    tag: 'Paid Service',
    tagColor: 'text-amber-700 bg-amber-50 border-amber-200',
    iconBg: 'bg-amber-50 text-amber-600 border border-amber-200',
    icon: ClipboardCheck,
    description: 'A vetted inspector physically checks the property against a standard checklist. Delivers a downloadable, shareable report that clearly separates what was physically observed from what was simply claimed by the landlord/agent.',
    metrics: [
      '42-Point On-Site Audit',
      'PDF Inspection Report',
      'Observed vs Claimed',
      'Timestamped Photos'
    ],
    dataSources: [
      'Trained, independent professional building and property auditors',
      'Standardized 42-point structural, electrical, and plumbing checklists',
      'Water pressure and salinity test kits on site',
      'High-resolution, unedited, geo-tagged and timestamped photo logs'
    ],
    benefits: [
      'Essential for diaspora and remote renters who cannot inspect in person',
      'Reveals painted-over mold, water pressure drops, and sewage odors',
      'Distinguishes between claimed amenities and functional reality',
      'Shareable PDF report for family consultations and landlord negotiations'
    ],
    operationalDetails: 'Inspectors are independent contractors penalized for false confirmations. Reports clearly separate "Physically Confirmed by Auditor" from "Landlord Claimed".'
  },
  {
    id: 6,
    title: '6. Property & Landlord Verification',
    tag: 'Optional Service',
    tagColor: 'text-purple-700 bg-purple-50 border-purple-200',
    iconBg: 'bg-purple-50 text-purple-600 border border-purple-200',
    icon: UserCheck,
    description: 'A vetted check on property existence, address, landlord/agent identity, price, availability, and condition — following a defined SOP (request → evidence collection → verification → checklist → review → result), with time-bound statuses (Verified, Verification Due, Under Review, Verification Expired, Verification Suspended).',
    metrics: [
      '6-Step SOP Audit',
      '5 Time-Bound Statuses',
      'ID & Title Check',
      'Anti-Fraud Guard'
    ],
    dataSources: [
      'Direct government-issued landlord identification verification',
      'Deed of conveyance / registered title audit',
      'Agent licensing and direct mandate letters from property owners',
      'Physical site confirmation verifying address and structural readiness'
    ],
    benefits: [
      'Eliminates ghost listings and fake agent deposit wire scams',
      'Guarantees the person collecting your deposit has lawful leasing authority',
      'Protects against double-leasing scams where one flat is rented to 5 tenants',
      'Clear time-bound badges (Verified, Verification Due, Suspended)'
    ],
    operationalDetails: 'Adheres to strict SOP: Request → Evidence Collection → Direct Identity Match → Physical Site Verification → Senior Compliance Review → Time-Bound Badge.'
  },
  {
    id: 7,
    title: '7. Property Listings',
    tag: 'Context Layer',
    tagColor: 'text-cyan-700 bg-cyan-50 border-cyan-200',
    iconBg: 'bg-cyan-50 text-cyan-600 border border-cyan-200',
    icon: Building2,
    description: 'Sourced from partner agencies, verified agents/landlords, and nightly market monitoring — listings exist to give context to the intelligence layer, not as the core product.',
    metrics: [
      '3 Sourcing Channels',
      'Scraped + Partner Feeds',
      'Livability Overlay',
      'Deduplicated Units'
    ],
    dataSources: [
      'Direct API partner feeds from licensed property agencies',
      'Vetted landlord direct listing submissions with verified documentation',
      'Nightly automated scrapers across public portals',
      'AI deduplication clustering identical apartments listed across multiple brokers'
    ],
    benefits: [
      'Search properties with ground-truth Livability Scores attached upfront',
      'Filters out recurring bait-and-switch listings that are already rented',
      'Directly links active listings with flood maps and power reliability data',
      'Saves dozens of hours spent browsing stale classified ads'
    ],
    operationalDetails: 'Listings exist as a context canvas for the intelligence engine. Unverified listings carry prominent advisory notices until audited.'
  },
  {
    id: 8,
    title: '8. Reporting & Accuracy Flagging',
    tag: 'Community Audit',
    tagColor: 'text-rose-700 bg-rose-50 border-rose-200',
    iconBg: 'bg-rose-50 text-rose-600 border border-rose-200',
    icon: Flag,
    description: 'Renters can report inaccurate information on a verified property, triggering an internal review that may lead to correction, re-verification, suspension, or removal of Verified status.',
    metrics: [
      'Community Audit Flag',
      '48-Hour Review SLA',
      'Suspension Protocol',
      'Self-Healing Data'
    ],
    dataSources: [
      'Verified renter flag submissions with photo and utility evidence',
      'Resident community feedback loops across verified estate clusters',
      'Field auditor spot-checks triggered by threshold anomaly alerts',
      'Public transparency logs of suspended and revoked verification badges'
    ],
    benefits: [
      'Enforces total accountability on landlords and verified real estate agents',
      'Immediate warning badges applied if a transformer fails or drainage clogs',
      'Community-powered ground truth that prevents data staleness',
      'Zero tolerance for fraudulent or misleading verification profiles'
    ],
    operationalDetails: 'A verified flag shifts a property to "Under Review" immediately. If uncorrected within 72 hours, status drops to "Verification Suspended".'
  }
];

const SLIDES = [
  { id: 0, title: 'Introduction', label: '01 Intro' },
  { id: 1, title: 'Problem & Solution', label: '02 Problem & Solution' },
  { id: 2, title: 'Intelligence Engine', label: '03 Intelligence Engine' },
  { id: 3, title: 'Verification & Audits', label: '04 Verification & Audits' },
];

export default function App() {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [slideDirection, setSlideDirection] = useState(1);
  const [isHovered, setIsHovered] = useState(false);
  const [isJoinModalOpen, setIsJoinModalOpen] = useState(false);
  const [selectedFeature, setSelectedFeature] = useState<FeatureDetail | null>(null);

  const totalSlides = SLIDES.length;

  const nextSlide = () => {
    setSlideDirection(1);
    setCurrentSlide((prev) => (prev + 1) % totalSlides);
  };

  const prevSlide = () => {
    setSlideDirection(-1);
    setCurrentSlide((prev) => (prev - 1 + totalSlides) % totalSlides);
  };

  const goToSlide = (idx: number) => {
    setSlideDirection(idx > currentSlide ? 1 : -1);
    setCurrentSlide(idx);
  };

  // 10-second timer for carousel auto-advance
  useEffect(() => {
    if (isHovered || isJoinModalOpen || selectedFeature !== null) return;

    const timer = setInterval(() => {
      setSlideDirection(1);
      setCurrentSlide((prev) => (prev + 1) % totalSlides);
    }, 10000); // 10-second timer

    return () => clearInterval(timer);
  }, [isHovered, isJoinModalOpen, selectedFeature, totalSlides]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (isJoinModalOpen || selectedFeature !== null) return;
      if (e.key === 'ArrowRight') nextSlide();
      if (e.key === 'ArrowLeft') prevSlide();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isJoinModalOpen, selectedFeature]);

  return (
    <div className="min-h-screen bg-white text-[#08182B] font-['Plus_Jakarta_Sans',sans-serif] relative flex flex-col justify-between selection:bg-[#10B981] selection:text-white overflow-x-hidden">
      {/* Dynamic ambient background */}
      <AnimatedBackground />

      {/* Presentation Top Header */}
      <header className="relative z-20 max-w-7xl w-full mx-auto px-4 sm:px-6 py-4 flex items-center justify-between border-b border-slate-200/80 bg-white/80 backdrop-blur-md">
        
        {/* Brand */}
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#10B981] to-[#059669] flex items-center justify-center text-white shadow-md shadow-emerald-500/20 border border-emerald-400/30">
            <ShieldCheck className="w-6 h-6 stroke-[2.2]" />
          </div>
          <div>
            <span className="font-extrabold text-xl tracking-tight text-[#08182B]">
              Verifi<span className="text-[#10B981]">Rent</span>
            </span>
            <p className="text-[11px] text-slate-500 -mt-0.5 font-medium">Know Before You Rent</p>
          </div>
        </div>

        {/* Presentation Carousel Controls & 10s Timer Indicator */}
        <div className="flex items-center gap-2 sm:gap-4">
          
          {/* Slide Pills (Desktop) */}
          <div className="hidden md:flex items-center gap-1.5 bg-slate-100/90 p-1 rounded-xl border border-slate-200/80">
            {SLIDES.map((slide) => (
              <button
                key={slide.id}
                onClick={() => goToSlide(slide.id)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                  currentSlide === slide.id
                    ? 'bg-white text-[#08182B] shadow-xs font-bold border border-slate-200/60'
                    : 'text-slate-500 hover:text-slate-900'
                }`}
              >
                {slide.label}
              </button>
            ))}
          </div>

          {/* Slide Arrow Controls */}
          <div className="flex items-center gap-1">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={prevSlide}
              aria-label="Previous Slide"
              className="w-8 h-8 rounded-lg bg-slate-100 hover:bg-[#10B981] hover:text-white text-slate-700 border border-slate-200 flex items-center justify-center transition-colors cursor-pointer shadow-2xs"
            >
              <ChevronLeft className="w-4 h-4" />
            </motion.button>

            <span className="text-xs font-mono font-bold text-slate-600 px-2 min-w-[50px] text-center">
              {currentSlide + 1} / {totalSlides}
            </span>

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={nextSlide}
              aria-label="Next Slide"
              className="w-8 h-8 rounded-lg bg-slate-100 hover:bg-[#10B981] hover:text-white text-slate-700 border border-slate-200 flex items-center justify-center transition-colors cursor-pointer shadow-2xs"
            >
              <ChevronRight className="w-4 h-4" />
            </motion.button>
          </div>

          {/* Launching soon status badge */}
          <div className="hidden sm:flex items-center gap-2 text-xs font-mono text-slate-700 bg-emerald-50/70 border border-emerald-200 shadow-2xs px-3 py-1.5 rounded-full">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#10B981] opacity-75" />
              <span className="relative inline-flex rounded-full h-2 w-2 bg-[#10B981]" />
            </span>
            <span className="font-semibold text-emerald-900">Launching soon</span>
          </div>

        </div>
      </header>

      {/* 10-Second Timer Progress Bar across slides */}
      <div className="relative z-20 w-full h-1 bg-slate-100 overflow-hidden">
        <motion.div
          key={`${currentSlide}-${isHovered || isJoinModalOpen || selectedFeature !== null ? 'paused' : 'running'}`}
          initial={{ width: '0%' }}
          animate={{ width: isHovered || isJoinModalOpen || selectedFeature !== null ? '100%' : '100%' }}
          transition={{ 
            duration: isHovered || isJoinModalOpen || selectedFeature !== null ? 0 : 10, 
            ease: 'linear' 
          }}
          className={`h-full ${
            isHovered || isJoinModalOpen || selectedFeature !== null
              ? 'bg-amber-400' 
              : 'bg-gradient-to-r from-emerald-400 via-[#10B981] to-emerald-600'
          }`}
        />
      </div>

      {/* Main Carousel Presentation Area */}
      <main 
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        className="relative z-10 max-w-7xl w-full mx-auto px-4 sm:px-6 py-6 sm:py-10 flex-1 flex flex-col justify-center pb-28"
      >
        <AnimatePresence mode="wait" custom={slideDirection}>
          
          {/* SLIDE 1: Introduction to VerifiRent & What We Do */}
          {currentSlide === 0 && (
            <motion.div
              key="slide-0"
              custom={slideDirection}
              initial={{ opacity: 0, x: slideDirection > 0 ? 80 : -80 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: slideDirection > 0 ? -80 : 80 }}
              transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              className="space-y-8"
            >
              {/* Header Banner */}
              <div className="max-w-3xl space-y-4">
                <div className="inline-flex items-center gap-2 text-xs font-bold text-[#059669] uppercase tracking-widest bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
                  <span className="w-2 h-2 rounded-full bg-[#10B981]" />
                  <span>Neighbourhood Intelligence Platform · Not A Listing Site</span>
                </div>

                <h1 className="text-3xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight leading-[1.12] text-[#08182B]">
                  Pretty photos hide ugly truths.{' '}
                  <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#059669] via-emerald-600 to-[#08182B]">
                    Know before you rent.
                  </span>
                </h1>

                <p className="text-slate-600 text-sm sm:text-lg leading-relaxed font-normal">
                  In rental markets, renters pick a home from glossy photos and persuasive agent pitches—then discover blackouts, street flooding every downpour, or 90-minute commute chokeholds. <strong className="text-[#08182B] font-semibold">VerifiRent uncovers the ground truth behind the house before you sign a lease.</strong>
                </p>
              </div>

              {/* 3 Core Pillars Grid */}
              <div className="grid md:grid-cols-3 gap-5">
                
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-md shadow-slate-200/50 space-y-3 hover:border-emerald-400 transition-colors">
                  <div className="w-12 h-12 rounded-xl bg-emerald-50 text-[#059669] flex items-center justify-center border border-emerald-200">
                    <ShieldCheck className="w-6 h-6 stroke-[2.2]" />
                  </div>
                  <h3 className="text-base font-bold text-[#08182B]">0–100 Livability Score</h3>
                  <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
                    Deterministic scores computed across electricity reliability, flood risk, mobile network latency, water purity, safety, and commute times.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-md shadow-slate-200/50 space-y-3 hover:border-emerald-400 transition-colors">
                  <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center border border-blue-200">
                    <Sparkles className="w-6 h-6 stroke-[2.2]" />
                  </div>
                  <h3 className="text-base font-bold text-[#08182B]">Zero AI Hallucinations</h3>
                  <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
                    Our AI strictly translates pre-verified field facts into plain English narrative. It is strictly prohibited from guessing or fabricating numbers.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-md shadow-slate-200/50 space-y-3 hover:border-emerald-400 transition-colors">
                  <div className="w-12 h-12 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center border border-purple-200">
                    <ClipboardCheck className="w-6 h-6 stroke-[2.2]" />
                  </div>
                  <h3 className="text-base font-bold text-[#08182B]">Vetted Physical Audits</h3>
                  <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
                    Professional field inspectors audit properties on a 42-point rubric, separating what was claimed by an agent from what is physically true.
                  </p>
                </div>

              </div>

              {/* Bottom Quick-Proof Bar */}
              <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200/80 flex flex-wrap items-center justify-between gap-4 text-xs">
                <div className="flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full bg-[#10B981]" />
                  <span className="font-bold text-[#08182B]">The Bottom Line:</span>
                  <span className="text-slate-600">VerifiRent is an independent intelligence engine built to protect your deposit and peace of mind.</span>
                </div>
                <button
                  type="button"
                  onClick={() => setIsJoinModalOpen(true)}
                  className="text-[#059669] font-bold flex items-center gap-1 hover:underline cursor-pointer"
                >
                  <span>Explore Partnership or Waitlist</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </motion.div>
          )}

          {/* SLIDE 2: Why We Are Doing This: Problem & Solution */}
          {currentSlide === 1 && (
            <motion.div
              key="slide-1"
              custom={slideDirection}
              initial={{ opacity: 0, x: slideDirection > 0 ? 80 : -80 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: slideDirection > 0 ? -80 : 80 }}
              transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              className="space-y-8"
            >
              {/* Header */}
              <div className="space-y-2">
                <div className="inline-flex items-center gap-2 text-xs font-bold text-amber-700 uppercase tracking-widest bg-amber-50 px-3 py-1 rounded-full border border-amber-200">
                  <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
                  <span>Why We Are Doing This · The Problem & Solution</span>
                </div>
                <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#08182B] tracking-tight">
                  The Rental Gamble vs The Ground Truth
                </h2>
                <p className="text-slate-600 text-sm sm:text-base max-w-3xl">
                  Millions of renters lock 1–2 years of upfront savings into an apartment based on a 15-minute walkthrough, only to discover chronic infrastructure failures.
                </p>
              </div>

              {/* Side-by-Side Problem & Solution Grid */}
              <div className="grid md:grid-cols-2 gap-6">
                
                {/* The Problem Card */}
                <div className="bg-rose-50/40 p-6 sm:p-7 rounded-3xl border border-rose-200/80 space-y-4">
                  <div className="flex items-center justify-between pb-3 border-b border-rose-200/60">
                    <div className="flex items-center gap-2.5 text-rose-800 font-extrabold text-lg">
                      <AlertTriangle className="w-5 h-5 text-rose-600" />
                      <span>The Rental Trap (The Problem)</span>
                    </div>
                    <span className="text-[10px] font-mono font-bold uppercase text-rose-600 bg-rose-100 px-2 py-0.5 rounded">
                      Status Quo
                    </span>
                  </div>

                  <ul className="space-y-3 text-xs sm:text-sm text-slate-700">
                    <li className="flex items-start gap-2.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-rose-500 mt-2 shrink-0" />
                      <span><strong>1–2 Years Rent Locked Upfront:</strong> Once money is wired, you cannot move without forfeiting immense capital.</span>
                    </li>
                    <li className="flex items-start gap-2.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-rose-500 mt-2 shrink-0" />
                      <span><strong>Staged Photos & Dry-Season Visits:</strong> Inspecting in January hides that the access road turns into a lake by June.</span>
                    </li>
                    <li className="flex items-start gap-2.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-rose-500 mt-2 shrink-0" />
                      <span><strong>Untracked Fuel & Water Outlays:</strong> Rent is just 60% of living cost; hidden diesel bills and water tanker fees double your budget.</span>
                    </li>
                    <li className="flex items-start gap-2.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-rose-500 mt-2 shrink-0" />
                      <span><strong>Double-Leasing & Ghost Agents:</strong> Unverified middlemen advertising homes they have zero mandate to rent.</span>
                    </li>
                  </ul>
                </div>

                {/* The Solution Card */}
                <div className="bg-emerald-50/40 p-6 sm:p-7 rounded-3xl border border-emerald-200/80 space-y-4">
                  <div className="flex items-center justify-between pb-3 border-b border-emerald-200/60">
                    <div className="flex items-center gap-2.5 text-emerald-900 font-extrabold text-lg">
                      <CheckCircle2 className="w-5 h-5 text-[#10B981]" />
                      <span>The VerifiRent Standard (The Solution)</span>
                    </div>
                    <span className="text-[10px] font-mono font-bold uppercase text-[#059669] bg-emerald-100 px-2 py-0.5 rounded">
                      Ground Truth
                    </span>
                  </div>

                  <ul className="space-y-3 text-xs sm:text-sm text-slate-700">
                    <li className="flex items-start gap-2.5">
                      <CheckCircle2 className="w-4 h-4 text-[#10B981] mt-0.5 shrink-0" />
                      <span><strong>Know Before You Sign:</strong> Verified 0–100 Livability Scores across power, flood vulnerability, and network quality.</span>
                    </li>
                    <li className="flex items-start gap-2.5">
                      <CheckCircle2 className="w-4 h-4 text-[#10B981] mt-0.5 shrink-0" />
                      <span><strong>Observed vs Claimed Audits:</strong> Independent on-site inspectors test sockets, water salinity, roof leaks, and mobile reception.</span>
                    </li>
                    <li className="flex items-start gap-2.5">
                      <CheckCircle2 className="w-4 h-4 text-[#10B981] mt-0.5 shrink-0" />
                      <span><strong>Mathematical Living Budget:</strong> True cost calculators uncover generator fuel needs and service charges before negotiating.</span>
                    </li>
                    <li className="flex items-start gap-2.5">
                      <CheckCircle2 className="w-4 h-4 text-[#10B981] mt-0.5 shrink-0" />
                      <span><strong>Vetted Landlord Ownership:</strong> 6-step SOP verifying property deeds, landlord identity, and agent mandates.</span>
                    </li>
                  </ul>
                </div>

              </div>

              {/* Bottom Quote Note */}
              <div className="p-4 rounded-2xl bg-white border border-slate-200 shadow-xs flex items-center justify-between text-xs text-slate-600">
                <span>"Renters don't just rent walls; they rent the power grid, the drainage basin, and the road infrastructure."</span>
                <span className="font-bold text-[#08182B]">— The VerifiRent Manifesto</span>
              </div>
            </motion.div>
          )}

          {/* SLIDE 3: Core Features (The Intelligence Engine) */}
          {currentSlide === 2 && (
            <motion.div
              key="slide-2"
              custom={slideDirection}
              initial={{ opacity: 0, x: slideDirection > 0 ? 80 : -80 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: slideDirection > 0 ? -80 : 80 }}
              transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              className="space-y-6"
            >
              <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3">
                <div className="space-y-2">
                  <div className="inline-flex items-center gap-2 text-xs font-bold text-[#059669] uppercase tracking-widest bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
                    <Zap className="w-3.5 h-3.5 text-[#10B981]" />
                    <span>Core Features · Part 1: The Intelligence Engine</span>
                  </div>
                  <h2 className="text-3xl sm:text-4xl font-extrabold text-[#08182B] tracking-tight">
                    Mathematical Ground Truth For Every Home
                  </h2>
                  <p className="text-xs sm:text-sm text-slate-600">
                    Click any feature card below to view detailed assessment dimensions, data sources, and practical lease benefits.
                  </p>
                </div>

                <span className="text-xs font-mono text-slate-500 bg-slate-100 px-3 py-1 rounded-lg border border-slate-200 shrink-0">
                  Features 1–4 of 8
                </span>
              </div>

              {/* 4 Intelligence Feature Cards Grid */}
              <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {INTELLIGENCE_FEATURES.map((feature, idx) => {
                  const Icon = feature.icon;
                  return (
                    <motion.div
                      key={feature.id}
                      initial={{ opacity: 0, y: 15 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: idx * 0.08, duration: 0.35 }}
                      onClick={() => setSelectedFeature(feature)}
                      whileHover={{ 
                        y: -4, 
                        borderColor: 'rgba(16, 185, 129, 0.5)', 
                        backgroundColor: '#FFFFFF',
                        boxShadow: '0 14px 28px -6px rgba(16, 185, 129, 0.14)'
                      }}
                      className="bg-white p-5 rounded-2xl border border-slate-200 flex flex-col justify-between space-y-3 transition-all group cursor-pointer shadow-xs hover:border-[#10B981] select-none"
                    >
                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <div className={`w-10 h-10 rounded-xl ${feature.iconBg} flex items-center justify-center transition-transform group-hover:scale-105 shadow-2xs`}>
                            <Icon className="w-5 h-5 stroke-[2.2]" />
                          </div>
                          <span className={`text-[10px] font-mono px-2 py-0.5 rounded-md border font-bold ${feature.tagColor}`}>
                            {feature.tag}
                          </span>
                        </div>

                        <h3 className="text-sm sm:text-base font-bold text-[#08182B] tracking-tight group-hover:text-[#059669] transition-colors">
                          {feature.title}
                        </h3>

                        <p className="text-xs text-slate-600 leading-relaxed font-normal line-clamp-4">
                          {feature.description}
                        </p>
                      </div>

                      <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-[#059669] font-medium group-hover:text-[#047857]">
                        <span>View metrics & details</span>
                        <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                      </div>
                    </motion.div>
                  );
                })}
              </div>

              {/* Engine Highlights Bar */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">6 Living Dimensions</span>
                  <span className="text-[10px] text-slate-500">Power, Flood, Network, Water, Safety, Traffic</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">90-Day Freshness</span>
                  <span className="text-[10px] text-slate-500">Continuous telemetry & community updates</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">Zero AI Guesswork</span>
                  <span className="text-[10px] text-slate-500">AI solely narrates pre-verified numbers</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">Side-by-Side Matrix</span>
                  <span className="text-[10px] text-slate-500">Compare 2 to 4 properties simultaneously</span>
                </div>
              </div>
            </motion.div>
          )}

          {/* SLIDE 4: Core Services (Verification & On-Ground Audits) */}
          {currentSlide === 3 && (
            <motion.div
              key="slide-3"
              custom={slideDirection}
              initial={{ opacity: 0, x: slideDirection > 0 ? 80 : -80 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: slideDirection > 0 ? -80 : 80 }}
              transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              className="space-y-6"
            >
              <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3">
                <div className="space-y-2">
                  <div className="inline-flex items-center gap-2 text-xs font-bold text-purple-700 uppercase tracking-widest bg-purple-50 px-3 py-1 rounded-full border border-purple-200">
                    <FileCheck2 className="w-3.5 h-3.5 text-purple-600" />
                    <span>Core Services · Part 2: On-Ground Audits & Integrity</span>
                  </div>
                  <h2 className="text-3xl sm:text-4xl font-extrabold text-[#08182B] tracking-tight">
                    On-Ground Audits You Can Stake Your Deposit On
                  </h2>
                  <p className="text-xs sm:text-sm text-slate-600">
                    Click any service card below to view detailed inspection rubrics, fraud-guard SOPs, and community audit workflows.
                  </p>
                </div>

                <span className="text-xs font-mono text-slate-500 bg-slate-100 px-3 py-1 rounded-lg border border-slate-200 shrink-0">
                  Services 5–8 of 8
                </span>
              </div>

              {/* 4 Verification Service Feature Cards Grid */}
              <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {VERIFICATION_SERVICES.map((feature, idx) => {
                  const Icon = feature.icon;
                  return (
                    <motion.div
                      key={feature.id}
                      initial={{ opacity: 0, y: 15 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: idx * 0.08, duration: 0.35 }}
                      onClick={() => setSelectedFeature(feature)}
                      whileHover={{ 
                        y: -4, 
                        borderColor: 'rgba(16, 185, 129, 0.5)', 
                        backgroundColor: '#FFFFFF',
                        boxShadow: '0 14px 28px -6px rgba(16, 185, 129, 0.14)'
                      }}
                      className="bg-white p-5 rounded-2xl border border-slate-200 flex flex-col justify-between space-y-3 transition-all group cursor-pointer shadow-xs hover:border-[#10B981] select-none"
                    >
                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <div className={`w-10 h-10 rounded-xl ${feature.iconBg} flex items-center justify-center transition-transform group-hover:scale-105 shadow-2xs`}>
                            <Icon className="w-5 h-5 stroke-[2.2]" />
                          </div>
                          <span className={`text-[10px] font-mono px-2 py-0.5 rounded-md border font-bold ${feature.tagColor}`}>
                            {feature.tag}
                          </span>
                        </div>

                        <h3 className="text-sm sm:text-base font-bold text-[#08182B] tracking-tight group-hover:text-[#059669] transition-colors">
                          {feature.title}
                        </h3>

                        <p className="text-xs text-slate-600 leading-relaxed font-normal line-clamp-4">
                          {feature.description}
                        </p>
                      </div>

                      <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-[#059669] font-medium group-hover:text-[#047857]">
                        <span>View metrics & details</span>
                        <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                      </div>
                    </motion.div>
                  );
                })}
              </div>

              {/* Service Highlights Bar */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">42-Point Checklist</span>
                  <span className="text-[10px] text-slate-500">Structural, electrical, plumbing & water pressure</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">6-Step Verification SOP</span>
                  <span className="text-[10px] text-slate-500">Title match, ID check & authorized mandate</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">Context Listings</span>
                  <span className="text-[10px] text-slate-500">Properties matched with intelligence layers</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 text-center">
                  <span className="block text-xs font-bold text-[#08182B]">Community Flagging</span>
                  <span className="text-[10px] text-slate-500">48-hour SLA review for flagged anomalies</span>
                </div>
              </div>
            </motion.div>
          )}

        </AnimatePresence>
      </main>

      {/* PERSISTENT FLOATING "JOIN US NOW" ACTION BUTTON */}
      <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-40">
        <motion.button
          whileHover={{ scale: 1.05, y: -2 }}
          whileTap={{ scale: 0.95 }}
          onClick={() => setIsJoinModalOpen(true)}
          aria-label="Open Join or Partner Modal"
          className="bg-gradient-to-r from-[#10B981] via-emerald-600 to-[#08182B] text-white px-6 sm:px-8 py-3.5 rounded-full font-extrabold text-sm sm:text-base shadow-xl shadow-emerald-600/30 border border-emerald-400/40 flex items-center gap-3 cursor-pointer backdrop-blur-md"
        >
          <Sparkles className="w-5 h-5 text-emerald-200 animate-pulse" />
          <span>Join Us Now</span>
          <span className="hidden sm:inline-block w-1.5 h-1.5 rounded-full bg-white/60" />
          <span className="hidden sm:inline text-xs font-medium text-emerald-100">
            Partner or Waitlist
          </span>
          <ArrowRight className="w-4 h-4 ml-1 text-emerald-200" />
        </motion.button>
      </div>

      {/* Presentation Footer */}
      <footer className="relative z-10 border-t border-slate-200/80 bg-white/90 backdrop-blur-md py-4">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-500">
          
          <div className="flex items-center gap-2">
            <span>© {new Date().getFullYear()} VerifiRent Technologies Ltd.</span>
            <span>·</span>
            <span className="font-medium text-slate-600">Neighbourhood Intelligence</span>
          </div>

          <div className="flex items-center gap-4 text-[11px] font-mono">
            <span className="text-slate-400">
              {isHovered ? '• Timer paused on hover' : '• 10s presentation timer active'}
            </span>
            <span className="hidden sm:inline text-slate-300">|</span>
            <span className="hidden sm:inline text-slate-400">
              Use ← and → arrow keys to navigate
            </span>
          </div>

        </div>
      </footer>

      {/* DUAL-SECTION JOIN / PARTNER MODAL */}
      <JoinModal 
        isOpen={isJoinModalOpen} 
        onClose={() => setIsJoinModalOpen(false)} 
      />

      {/* CENTRALIZED FEATURE DETAIL OVERLAY COMPONENT */}
      <FeatureDetailModal 
        feature={selectedFeature} 
        onClose={() => setSelectedFeature(null)} 
        onJoinWaitlistClick={() => {
          setSelectedFeature(null);
          setIsJoinModalOpen(true);
        }}
      />
    </div>
  );
}
